//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akademinya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlisverisSepeti
    {
        public int Id { get; set; }
        public Nullable<int> KursID { get; set; }
        public string Guid { get; set; }
    
        public virtual Kurs Kurs { get; set; }
    }
}
