//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akademinya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kartlar
    {
        public int Id { get; set; }
        public Nullable<int> UyeID { get; set; }
        public string KayitAdi { get; set; }
        public string KartNo { get; set; }
        public string KartUstundekiIsım { get; set; }
        public int Ay { get; set; }
        public int Yil { get; set; }
        public string Cvc { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Uye Uye { get; set; }
    }
}
